name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.15]  # Adjust according to your Node.js version

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      
    - name: Install server dependencies
      run: npm ci
      
    - name: Install client dependencies
      run: cd client && npm ci
      
    - name: Run server tests
      run: npm test
      
    - name: Run client tests
      run: cd client && npm test

    # Uncomment these lines if you want to build your Svelte app
    # - name: Build client app
    #   run: cd client && npm run build
